# Generated by Django 4.1.1 on 2022-11-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_state", models.CharField(max_length=50)),
                ("hotel_city", models.CharField(max_length=50)),
                ("hotel_district", models.CharField(max_length=50)),
                ("hotel_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("hotel_star", models.CharField(max_length=50)),
                ("hotel_house_n", models.IntegerField()),
                ("hotel_single_n", models.IntegerField()),
                ("hotel_double_n", models.IntegerField()),
                ("hotel_family_n", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rst_state", models.CharField(max_length=50)),
                ("rst_city", models.CharField(max_length=50)),
                ("rst_district", models.CharField(max_length=50)),
                ("rst_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("rst_open_time", models.TimeField()),
                ("rst_close_time", models.TimeField()),
                ("rst_cookies_n", models.IntegerField()),
                ("rst_star", models.CharField(max_length=50)),
                ("rst_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TourPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_state", models.CharField(max_length=50)),
                ("tour_city", models.CharField(max_length=50)),
                ("tour_district", models.CharField(max_length=50)),
                ("tour_price", models.DecimalField(decimal_places=5, max_digits=10)),
                ("tour_open_time", models.TimeField()),
                ("tour_close_time", models.TimeField()),
                ("tour_area", models.DecimalField(decimal_places=5, max_digits=10)),
                ("tour_capacity", models.IntegerField()),
                ("tour_build_date", models.DateField(max_length=50)),
            ],
        ),
    ]
